name: deploy

on:
  push:
    branches:
      - main

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install OctoDNS
        run: pip install 'octodns==0.9.10'
      - name: Sync w/ production DNS providers
        run: ./bin/sync
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
